Add Scala 3 support
scalacenter/bloop-config pull request #101
Opened 2024-10-05 13:41 UTC by kubukoz

To unblock Bloop's ability to cross-build sbt-bloop for sbt 2.0 (https://github.com/sbt/sbt/issues/7698).

2024-10-05 13:42 UTC, kubukoz commented on build.sc
> +    // note: somehow, this doesn't work (causes "Please override mimaPreviousVersions or mimaPreviousArtifacts")
thought: I didn't spend too much time on it, hoping someone with more Mill experience can provide a better understanding and maybe a proper fix. This seems like something that only affects us until we publish the 3.x support.

2024-10-05 13:43 UTC, kubukoz commented on config/src-3/bloop/config/SourceGeneratorCompanionPlatform.scala
> +trait SourceGeneratorCompanionPlatform {}
thought: `extends AbstractFunction3` was causing a "missing apply method" in Scala 3. Adding that `apply` was conflicting with the other `apply` - hence, version-specific sources.

2024-10-07 08:09 UTC, tgodzik requested changes
Thanks! We might want to switch to JDK 11 since jsoniter dropped support for JDK 8, which should not be an issue for the tools using bloop-config.

Also, looks like scalafix is not passing. We can disable it for Scala 3 if it proves to difficult to fix.

2024-10-12 11:37 UTC, kubukoz commented
Tried just disabling `removeUnused` for Scala 3 this way:

```scala
  def extraArgs = T {
    if(scalaVersion() == scala3) List("---settings.OrganizeImports.removeUnused=false")
    else Nil
  }

  override def fix(args: String*): Command[Unit] = T.command {
    val allArgs = args ++ extraArgs()

    super.fix(allArgs: _*)()
  }
```

but Mill complains:

```
[error] bloop-config/build.sc:73:15: Target#apply() call cannot use `value allArgs` defined within the T{...} block
[error]     super.fix(allArgs: _*).apply()
[error]               ^
[error] one error found
1 targets failed
```

which I don't really understand yet...

2024-10-13 15:49 UTC, tgodzik approved these changes
Should be fixed now, should we do a release now?

2024-10-13 15:49 UTC, merged

2024-10-13 21:36 UTC, kubukoz commented
Can't hurt 😅